spring:
  datasource:
    url: 'jdbc:mysql://120.46.159.231:3306/2022212864?createDatabaseIfNotExist=true'
    username: '2022212864'
    password: '2022212864'
    hikari:
      maximum-pool-size: 5
  sql:
    init:
      mode: always

logging:
  level:
    sql: debug
    org:
      example: debug
    com:
      nightlos: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'
